// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBieYFF0MbSnxRde82anPnkxJ4jyriAz2o',
    appId: '1:762585809218:web:c1918968e3ede4256588db',
    messagingSenderId: '762585809218',
    projectId: 'gradproject-6d49d',
    authDomain: 'gradproject-6d49d.firebaseapp.com',
    storageBucket: 'gradproject-6d49d.appspot.com',
    measurementId: 'G-C94BX84X6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz36ubCL0_Axkyn3flwcdgNh9MlmQpKdY',
    appId: '1:762585809218:android:8630934756a07d0f6588db',
    messagingSenderId: '762585809218',
    projectId: 'gradproject-6d49d',
    storageBucket: 'gradproject-6d49d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPIEzUV4qFx5AFDL0G60X1oRaoU1EnfhU',
    appId: '1:762585809218:ios:78a6933c962a48d06588db',
    messagingSenderId: '762585809218',
    projectId: 'gradproject-6d49d',
    storageBucket: 'gradproject-6d49d.appspot.com',
    iosClientId: '762585809218-jgmu68k3840nmhm9t2f09aumk2apivmt.apps.googleusercontent.com',
    iosBundleId: 'com.finalgradproj.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPIEzUV4qFx5AFDL0G60X1oRaoU1EnfhU',
    appId: '1:762585809218:ios:f5af8e08154b88016588db',
    messagingSenderId: '762585809218',
    projectId: 'gradproject-6d49d',
    storageBucket: 'gradproject-6d49d.appspot.com',
    iosClientId: '762585809218-ijh3bjd63l7fhc8mr34i9a3d08v27uus.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGradProject',
  );
}
